name: Daily GitHub Activity

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 0 点触发
  workflow_dispatch:

jobs:
  daily-activity:
    runs-on: ubuntu-latest

    steps:
      # 拉取仓库
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      # 随机延迟 0~24 小时，模拟随机时间
      - name: Random delay
        run: |
          DELAY=$((RANDOM % 1))
          echo "等待 $DELAY 秒再执行..."
          sleep $DELAY

      # 确保 update.md 文件存在
      - name: Ensure update.md exists
        run: |
          if [ ! -f update.md ]; then
            echo "# Daily Commit Log" > update.md
          fi

      # 清理 7 天前日志
      - name: Clean up logs older than 7 days
        run: |
          find . -name "update.md" -mtime +7 -exec rm -f {} \;
          echo "清理完 7 天前日志"

      # 提交每日日志（Commit）
      - name: Append daily log
        run: |
          echo "$(TZ='Asia/Shanghai' date '+%Y-%m-%d %H:%M:%S') - 自动提交日志 🌱" >> update.md
      - name: Commit and push log
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add update.md
          git commit -m "chore: daily log update" || echo "No changes to commit"
          git push

      # 随机创建 Issue（40% 概率，测试版保持 100%）
      - name: Randomly create Issue
        run: |
          RAND=$((RANDOM % 100))
          if [ $RAND -lt 100 ]; then
            echo "生成每日 Issue"
            gh issue create --title "Daily Issue - $(TZ='Asia/Shanghai' date '+%Y-%m-%d')" \
                             --body "随机生成每日 Issue 🌱" \
                             --repo $GITHUB_REPOSITORY
          fi
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      # 随机创建 PR（20% 概率，测试版保持 100%）
      - name: Randomly create PR
        run: |
          RAND=$((RANDOM % 100))
          if [ $RAND -lt 100 ]; then
            BRANCH="daily-pr-$(date '+%Y%m%d%H%M%S')"
            git checkout -b $BRANCH
            echo "$(TZ='Asia/Shanghai' date '+%Y-%m-%d %H:%M:%S') - 自动 PR 日志 🌱" >> update.md
            git add update.md
            git commit -m "chore: daily PR update"
            git push origin $BRANCH
            gh pr create --title "Daily PR - $(TZ='Asia/Shanghai' date '+%Y-%m-%d')" \
                         --body "随机生成每日 PR 🌱" \
                         --base main \
                         --head $BRANCH \
                         --repo $GITHUB_REPOSITORY
          fi
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      # 自动对开源仓库 PR 做 Code Review（贡献图真实显示）
      - name: Auto Code Review on external repo
        run: |
          TARGET_REPO="Daily Quests"  # 替换为你想 review 的仓库
          PR_LIST=$(gh pr list --state open --repo $TARGET_REPO --json number -q '.[].number')

          if [ -z "$PR_LIST" ]; then
            echo "没有找到可 review 的 PR"
            exit 0
          fi

          # 随机选一个 PR
          PR_NUM=$(echo "$PR_LIST" | shuf -n1)
          echo "准备对 PR #$PR_NUM 进行自动 Review"
          gh pr review $PR_NUM --approve --body "🤖 自动 Review: 看起来不错！"
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
