name: Test Code Review Activity

on:
  workflow_dispatch:       # 手动触发

jobs:
  code-review:
    runs-on: ubuntu-latest

    steps:
      # 拉取仓库
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      # ----- 随机给 PR 进行代码审查 (30% 概率) (增加 Code Reviews) -----
      - name: Randomly add code review comment
        run: |
          RAND=$((RANDOM % 100))
          if [ $RAND -lt 30 ]; then
            # 获取第一个打开的 PR URL 和 PR 作者
            PR_INFO=$(gh pr list --state open --repo $GITHUB_REPOSITORY --json url,author -q '.[0]')
            PR_URL=$(echo "$PR_INFO" | jq -r '.url')
            PR_AUTHOR=$(echo "$PR_INFO" | jq -r '.author.login')

            # 获取当前 GitHub 用户名
            CURRENT_USER=$(gh api user -q '.login')

            # 检查 PR 作者是否是当前用户
            if [ "$PR_AUTHOR" != "$CURRENT_USER" ]; then
              if [ -n "$PR_URL" ]; then
                echo "Adding review comment to PR: $PR_URL"
                gh pr review $PR_URL --approve --body "Good work! Keep it up! 🌱"
              else
                echo "No open PR found to review."
              fi
            else
              echo "Skipping review for your own PR."
            fi
          else
            echo "今天不进行代码审查"
          fi
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
