name: Daily Random GitHub Activity

on:
  schedule:
    - cron: '0 0 * * *'  # UTC 0 点触发工作流，每天触发
  workflow_dispatch:       # 手动触发

jobs:
  daily-activity:
    runs-on: ubuntu-latest

    steps:
      # 拉取仓库
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      # 随机延迟（模拟随机时间执行）
      - name: Wait for random delay
        run: |
          DELAY=$((RANDOM % 1))  # 随机延迟 0 到 86400 秒（即 24 小时内的随机时间）
          echo "Waiting for $DELAY seconds before starting actions..."
          sleep $DELAY

      # 确保 update.md 文件存在
      - name: Ensure update.md exists
        run: |
          if [ ! -f update.md ]; then
            echo "# Daily Commit Log" > update.md
          fi

      # ----- 清理 7 天前的日志 -----
      - name: Clean up logs older than 7 days
        run: |
          find . -name "update.md" -mtime +7 -exec rm -f {} \;
          echo "Cleaned up logs older than 7 days."

      # ----- 随机提交日志 (增加 Commits) -----
      - name: Append random log
        run: |
          echo "$(TZ='Asia/Shanghai' date '+%Y-%m-%d %H:%M:%S') - 自动提交日志 🌱" >> update.md

      - name: Commit and push log
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add update.md
          git commit -m "chore: daily log update" || echo "No changes to commit"
          git push

      # ----- 随机创建每日 Issue (30% 概率) (增加 Issues) -----
      - name: Randomly create daily issue
        run: |
          RAND=$((RANDOM % 100))
          if [ $RAND -lt 30 ]; then
            echo "生成每日 Issue"
            gh issue create --title "Daily Issue - $(TZ='Asia/Shanghai' date '+%Y-%m-%d')" \
                             --body "随机生成每日 Issue 🌱" \
                             --repo $GITHUB_REPOSITORY
          else
            echo "今天不生成 Issue"
          fi
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      # ----- 随机创建每日 PR (30% 概率) (增加 Pull Requests) -----
      - name: Randomly create daily PR
        run: |
          RAND=$((RANDOM % 100))
          if [ $RAND -lt 30 ]; then
            BRANCH="daily-pr-$(date '+%Y%m%d%H%M%S')"
            git checkout -b $BRANCH
            echo "$(TZ='Asia/Shanghai' date '+%Y-%m-%d %H:%M:%S') - 自动 PR 日志 🌱" >> update.md
            git add update.md
            git commit -m "chore: daily PR update"
            git push origin $BRANCH
            gh pr create --title "Daily PR - $(TZ='Asia/Shanghai' date '+%Y-%m-%d')" \
                         --body "随机生成每日 PR 🌱" \
                         --base main \
                         --head $BRANCH \
                         --repo $GITHUB_REPOSITORY
          else
            echo "今天不生成 PR"
          fi
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      # ----- 随机给 PR 进行代码审查 (30% 概率) (增加 Code Reviews) -----
      - name: Randomly add code review comment
        run: |
          RAND=$((RANDOM % 100))
          if [ $RAND -lt 30 ]; then
            # 获取第一个打开的 PR URL 和 PR 作者
            PR_INFO=$(gh pr list --state open --repo $GITHUB_REPOSITORY --json url,author -q '.[0]')
            PR_URL=$(echo "$PR_INFO" | jq -r '.url')
            PR_AUTHOR=$(echo "$PR_INFO" | jq -r '.author.login')

            # 获取当前 GitHub 用户名
            CURRENT_USER=$(gh api user -q '.login')

            # 检查 PR 作者是否是当前用户
            if [ "$PR_AUTHOR" != "$CURRENT_USER" ]; then
              if [ -n "$PR_URL" ]; then
                echo "Adding review comment to PR: $PR_URL"
                gh pr review $PR_URL --approve --body "Good work! Keep it up! 🌱"
              else
                echo "No open PR found to review."
              fi
            else
              echo "Skipping review for your own PR."
            fi
          else
            echo "今天不进行代码审查"
          fi
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
