name: Daily Random GitHub Activity

on:
  schedule:
    - cron: '0 0 * * *'   # 每天 UTC 0点触发
  workflow_dispatch:       # 支持手动触发

jobs:
  daily-activity:
    runs-on: ubuntu-latest

    steps:
      # 拉取仓库
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      # 随机延迟（0~24小时内随机时间执行）
      - name: Wait for random delay
        run: |
          DELAY=$((RANDOM % 1))
          echo "Waiting $DELAY seconds..."
          sleep $DELAY

      # 确保 update.md 文件存在
      - name: Ensure update.md exists
        run: |
          if [ ! -f update.md ]; then
            echo "# 📅 Daily GitHub Activity Log" > update.md
            echo "" >> update.md
          fi

      # 随机提交日志
      - name: Append random log
        run: |
          echo "## $(TZ='Asia/Shanghai' date '+%Y-%m-%d')" >> update.md
          echo "- 📝 Commit: 自动提交日志 🌱" >> update.md
          echo "" >> update.md

      - name: Commit and push log
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add update.md
          git commit -m "chore: daily log update" || echo "No changes"
          git push origin HEAD:main

      # 随机 Issue (30%)
      - name: Random Issue
        run: |
          RAND=$((RANDOM % 100))
          DAY=$(TZ='Asia/Shanghai' date '+%Y-%m-%d')
          if [ $RAND -lt 100 ]; then
            ISSUE_URL=$(gh issue create \
                        --title "Daily Issue - $DAY" \
                        --body "随机生成每日 Issue 🌱" \
                        --repo $GITHUB_REPOSITORY | tail -n 1)
            echo "- 🐛 Issue: $ISSUE_URL" >> update.md
          else
            echo "- 🐛 Issue: 无" >> update.md
          fi
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      # 随机 PR (30%)
      - name: Random PR
        run: |
          RAND=$((RANDOM % 100))
          DAY=$(TZ='Asia/Shanghai' date '+%Y-%m-%d')
          if [ $RAND -lt 100 ]; then
            BRANCH="daily-pr-$(date '+%Y%m%d%H%M%S')"
            git checkout -b $BRANCH
            echo "- 🔀 PR Commit: 自动 PR 日志 🌱" >> update.md
            git add update.md
            git commit -m "chore: daily PR update"
            git push origin $BRANCH
            PR_URL=$(gh pr create \
                      --title "Daily PR - $DAY" \
                      --body "随机生成每日 PR 🌱" \
                      --base main --head $BRANCH \
                      --repo $GITHUB_REPOSITORY | tail -n 1)
            echo "- 🔀 PR: $PR_URL" >> update.md
          else
            echo "- 🔀 PR: 无" >> update.md
          fi
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      # 随机 Code Review (30%)
      - name: Random Review
        run: |
          RAND=$((RANDOM % 100))
          if [ $RAND -lt 100 ]; then
            PR_URL=$(gh pr list --state open --repo $GITHUB_REPOSITORY | head -n 1 | awk '{print $1}')
            if [ -n "$PR_URL" ]; then
              echo "Reviewing PR #$PR_URL"
              gh pr review $PR_URL --approve --body "LGTM 👍 自动审核"
              echo "- 👀 Review: 已审核 PR #$PR_URL" >> update.md
            else
              echo "- 👀 Review: 无可用 PR" >> update.md
            fi
          else
            echo "- 👀 Review: 未执行" >> update.md
          fi
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      # 更新 update.md (把 Issue/PR/Review 写进去)
      - name: Final Commit
        run: |
          git add update.md
          git commit -m "chore: update daily log (issues/pr/reviews)" || echo "No changes"
          git push origin HEAD:main
