name: Daily GitHub Activity

on:
  workflow_dispatch:   # 手动触发
  workflow_call:       # 允许被 scheduler.yml 调用

jobs:
  daily-activity:
    runs-on: ubuntu-latest

    steps:
      # 拉取仓库
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}

      # 设置时区为北京时间
      - name: Set timezone to Asia/Shanghai
        run: sudo timedatectl set-timezone Asia/Shanghai

      # 确保日志文件存在
      - name: Ensure update.md exists
        run: |
          if [ ! -f update.md ]; then
            echo "# Daily Commit Log" > update.md
          fi

      # 开场白
      - name: Write daily intro
        run: |
          LOG_DATE=$(date '+%Y-%m-%d')
          echo -e "\n## $LOG_DATE" >> update.md
          MOODS=("✨ 开始今天的 Github 冒险！" "☕ 边喝咖啡边写点代码～" "🛠️ 今天也要折腾一番！" "📖 记录一下日常操作")
          echo "${MOODS[$RANDOM % ${#MOODS[@]}]}" >> update.md

      # 日常日志
      - name: Append random logs
        run: |
          LOG_FILE="update.md"
          for i in $(seq 1 $((RANDOM % 3 + 1))); do
            NOW=$(date '+%H:%M:%S')
            THOUGHTS=("🌱 随手记下一笔" "✍️ 突然想到点东西" "🚀 来一发 PR" "📌 打个小补丁" "🎯 试试新点子")
            echo "[$NOW] ${THOUGHTS[$RANDOM % ${#THOUGHTS[@]}]}" >> $LOG_FILE
          done

      # 提交日志（加 stash 避免冲突）
      - name: Commit and push log
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add update.md
          git commit -m "chore: daily log update" || echo "No changes"
          git stash
          git pull --rebase origin main || true
          git stash pop || true
          git push origin main

      # 日终总结
      - name: Write summary
        run: |
          echo "🌙 今日小结：完成了一些提交/Issue/PR/Star ⭐" >> update.md
          git add update.md
          git commit -m "chore: daily summary" || echo "No changes"
          git stash
          git pull --rebase origin main || true
          git stash pop || true
          git push origin main
