name: Daily Random Scheduler

on:
  schedule:
    - cron: '0 0 * * *'   # 每天 UTC 0 点触发（北京时间 8 点）
  workflow_dispatch:       # 允许手动执行

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Decide random runs
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          echo "列出仓库里的所有 workflow，方便调试："
          gh workflow list -R $GITHUB_REPOSITORY

          COUNT=$((RANDOM % 4 + 2))   # 每天 2~5 次
          echo "今天要执行 $COUNT 次 Daily GitHub Activity"

          for i in $(seq 1 $COUNT); do
            DELAY=$((RANDOM % 10800))   # 每次延迟 0~3 小时
            echo "第 $i 次任务将在延迟 $DELAY 秒后执行"
            nohup bash -c "sleep $DELAY && gh workflow run 'Daily GitHub Activity' -R $GITHUB_REPOSITORY" &
          done
